spring.application.name: demo-producer
server.port: 9001
rocketmq.name-server: 127.0.0.1:9876
#mq的nameserver地址
rocketmq.producer.namesrvAddr: 127.0.0.1:9876
demo.rocketmq.topic: string-topic
demo.rocketmq.orderTopic: order-paid-topic
demo.rocketmq.msgExtTopic: message-ext-topic
demo.rocketmq.transTopic: spring-transaction-topic

###producer
#该应用是否启用生产者
rocketmq.producer.isOnOff: on
#发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
rocketmq.producer.groupName: ${spring.application.name}
#发送消息超时时间,默认3000
rocketmq.producer.sendMsgTimeout: 3000
#发送消息失败重试次数，默认2
rocketmq.producer.retryTimesWhenSendFailed: 2

###consumer
##该应用是否启用消费者
rocketmq.consumer.isOnOff: on
#mq的nameserver地址
rocketmq.consumer.namesrvAddr: 127.0.0.1:9876
#该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
rocketmq.consumer.topics: DemoTopic~*;
rocketmq.consumer.consumeThreadMin: 20
rocketmq.consumer.consumeThreadMax: 64
#设置一次消费消息的条数，默认为1条
rocketmq.consumer.consumeMessageBatchMaxSize: 1